Prefix: '&a[&cTnTCore&a] &e'
Messages:
  Errors:
    no-exist: '&cEste comando no existe.'
    no-console: '&cEste comando no esta disponible para consola.'
  Check:
    player: '&aEl plugin esta funcionando. Comando ejecutado des del jugador'
    console: '&aEl plugin esta funcionando. Comando ejecutado des de la consola.'
  Death:
    msg: '&c&lEl comienzo del sufrimiento infinito de &4&l%player% &c&lha comenzado!'
    coords-enable: true
    coords-msg: '&7&oX:%x% || Y:%y% || Z:%z%'
    train: '&c¡Comienza el Death Train con duración de %time% horas!'
    train-actionbar: '&7Quedan %time% de tormenta'
    title: '&c¡Boom!'
    subtitle: '&e¡%player% &cexploto!'
    players:
      GuerreroCraft61: ''
Sleep:
  msg: '&e%player% ha dormido'
  explosive: true
Storm:
  end-msg: '&aLa tormenta ha llegado a su fin'
  AddSeconds: 1800
Totem:
  fail-enable: true
  probability: 5
  msg-fail: '&7¡El totem de &c%player% &7ha fallado!'
  msg-used-totem: '&7El jugador %player% ha usado un totem (Probabilidad: %totem_fail% %porcent% %number%)'
MainWorld: world
