Death:
  msg-enable: true
  coords-enable: true
Sleep:
  explosive: false #Esta bug
Storm:
  enable: false
  add-seconds: 720 #12 minutos
  sound-enable: true
  title-enable: true
  actionbar-enable: false
  actionbar-delay: 60 #1 minuto
Totem:
  fail-enable: true
  probability: 5
MainWorld: "world"
CustomIP:
  enable: true
  IP: "***REMOVED***"