Prefix: "&a[&cTnTCore&a] &e"
Death:
  coords-enable: true
Sleep:
  explosive: false #Esta bug
Storm:
  enable: false
  add-seconds: 720 #12 minutos
  sound-enable: true
  title-enable: true
Totem:
  fail-enable: true
  probability: 5
MainWorld: "world"
CustomIP:
  enable: true
  IP: "***REMOVED***"