main: ${mainClass}
version: ${version}
name: ${name}
api-version: ${api-version}
author: ${author}
description: ${description}
website: ${url}

commands:
  tnt:
    description: comando principal
    usage: /tnt <subcomando>